services:
  postgres:
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:5432"

  backend:
    ports:
      - "${BACKEND_EXTERNAL_PORT}:8000"

  service:
    ports:
      - "${SERVICE_EXTERNAL_PORT}:8000"

  frontend:
    ports:
      - "${FRONTEND_EXTERNAL_PORT}:80"

  db-admin:
    image: adminer:4
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - "${DB_ADMIN_EXTERNAL_PORT}:8085"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
